# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      go-dependencies:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directories:
      - "/deploy/local/compose/go"
      - "/deploy/local/compose/postgres"
      - "/deploy/local/compose/garage"
      - "/deploy/production/compose/go"
      - "/deploy/production/compose/postgres"
    schedule:
      interval: "monthly"
    groups:
      docker-images:
        patterns:
          - "*"
