#!/bin/bash
# deploy/production/compose/go/start

set -o errexit
set -o pipefail
set -o nounset

echo "Running database migrations..."
/app/bin/server migrate up

echo "Starting server..."
exec /app/bin/server api
